Repository TEAM-DAWM/SHELLIN-SERVER, pull requests merged in 2024-07, with the labels that each got.

#4 [feat] security 구현 완료
  build.gradle
  src/main/java/nutshell/server/advice/GlobalExceptionHandler.java
  src/main/java/nutshell/server/annotation/UserId.java
  src/main/java/nutshell/server/constant/AuthConstant.java
  src/main/java/nutshell/server/controller/TestController.java
  src/main/java/nutshell/server/dto/auth/JwtTokensDto.java
  src/main/java/nutshell/server/dto/test/TestDto.java
  src/main/java/nutshell/server/dto/test/TestInput.java
  src/main/java/nutshell/server/exception/code/UnAuthorizedErrorCode.java
  src/main/java/nutshell/server/security/config/SecurityConfig.java
  src/main/java/nutshell/server/security/filter/JwtAuthenticationFilter.java
  src/main/java/nutshell/server/security/filter/JwtExceptionFilter.java
  src/main/java/nutshell/server/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/nutshell/server/security/info/UserAuthentication.java
  src/main/java/nutshell/server/utils/JwtUtil.java
Labels: :zap: feat

#9 [feat] Token 엔티티 생성 with Redis
  build.gradle
  src/main/java/nutshell/server/domain/Token.java
Labels: :zap: feat

#13 [feat] GoogleCalender 엔티티 생성
  src/main/java/nutshell/server/domain/GoogleCalender.java
  src/main/java/nutshell/server/domain/User.java
Labels: :zap: feat

#17 [feat] 구글 소셜 로그인 API 구현
  build.gradle
  dump.rdb
  src/main/java/nutshell/server/ServerApplication.java
  src/main/java/nutshell/server/constant/AuthConstant.java
  src/main/java/nutshell/server/controller/AuthController.java
  src/main/java/nutshell/server/controller/TestController.java
  src/main/java/nutshell/server/controller/swagger/UserControllerSwagger.java
  src/main/java/nutshell/server/domain/User.java
  src/main/java/nutshell/server/dto/SocialLoginResponse.java
  src/main/java/nutshell/server/dto/auth/JwtTokensDto.java
  src/main/java/nutshell/server/exception/code/NotFoundErrorCode.java
  src/main/java/nutshell/server/exception/code/UnAuthorizedErrorCode.java
  src/main/java/nutshell/server/feign/SuccessCode.java
  src/main/java/nutshell/server/feign/config/FeignConfig.java
  src/main/java/nutshell/server/feign/google/GoogleAuthClient.java
  src/main/java/nutshell/server/feign/google/GoogleInfoClient.java
  src/main/java/nutshell/server/feign/google/GoogleTokenResponse.java
  src/main/java/nutshell/server/feign/google/GoogleUserInfoResponse.java
  src/main/java/nutshell/server/repository/TokenRepository.java
  src/main/java/nutshell/server/repository/UserRepository.java
  src/main/java/nutshell/server/security/config/SecurityConfig.java
  src/main/java/nutshell/server/service/auth/AuthService.java
  src/main/java/nutshell/server/service/token/TokenRemover.java
  src/main/java/nutshell/server/service/token/TokenRetriever.java
  src/main/java/nutshell/server/service/token/TokenSaver.java
  src/main/java/nutshell/server/service/user/UserRetriever.java
  src/main/java/nutshell/server/utils/JwtUtil.java
Labels: :zap: feat

#24 [feat] Staging Area Task 생성 POST API 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/domain/Task.java
  src/main/java/nutshell/server/dto/task/TaskCreateDto.java
  src/main/java/nutshell/server/dto/task/TaskResponse.java
  src/main/java/nutshell/server/exception/code/NotFoundErrorCode.java
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/repository/UserRepository.java
  src/main/java/nutshell/server/service/task/TaskRemover.java
  src/main/java/nutshell/server/service/task/TaskRetriever.java
  src/main/java/nutshell/server/service/task/TaskSaver.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/task/TaskUpdater.java
  src/main/java/nutshell/server/service/user/UserRetriever.java
Labels: :zap: feat

#25 [fix] 응답 반환값 수정
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/service/task/TaskSaver.java
  src/main/java/nutshell/server/service/task/TaskService.java
Labels: :bug: fix

#27 [feat] Task DELETE API 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/service/task/TaskService.java
Labels: :zap: feat

#29 [fix] 자료형 변경 및 어노테이션 추가
  src/main/java/nutshell/server/dto/task/TaskCreateDto.java
  src/main/java/nutshell/server/dto/task/TaskResponse.java
  src/main/java/nutshell/server/repository/TaskRepository.java
Labels: :bug: fix

#30 [feat] Task 상세조회 GET API 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/dto/task/TaskDto.java
  src/main/java/nutshell/server/service/task/TaskService.java
Labels: :zap: feat

#32 [feat] Task 할당 날짜 PATCH API 구현
  src/main/java/nutshell/server/JacksonConfig.java
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/dto/task/TaskAssignedDto.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/task/TaskUpdater.java
Labels: :zap: feat

#36 [feat] Task의 설명을 수정하는 PATCH API 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/dto/task/TaskDetailEditDto.java
  src/main/java/nutshell/server/dto/task/TaskResponse.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/task/TaskUpdater.java
Labels: :zap: feat

#40 [fix] 구글 소셜 로그인 시 이름, 성, 사용자 이미지를 받아오기 위한 필드 추가
  src/main/java/nutshell/server/domain/User.java
  src/main/java/nutshell/server/service/auth/AuthService.java
  src/main/java/nutshell/server/service/user/UserRetriever.java
Labels: :bug: fix

#35 [feat] Task의 상태를 수정하고, 지연 시 지연 카운팅을 하는 PATCH API 구현
  src/main/java/nutshell/server/ServerApplication.java
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/domain/Defer.java
  src/main/java/nutshell/server/domain/Task.java
  src/main/java/nutshell/server/dto/task/TaskStatusDto.java
  src/main/java/nutshell/server/dto/type/Status.java
  src/main/java/nutshell/server/repository/DeferRepository.java
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/service/defer/DeferSaver.java
  src/main/java/nutshell/server/service/task/TaskRetriever.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/task/TaskUpdater.java
Labels: :zap: feat

#44 [refac] findByUserAndId로 조회 리팩토링
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/service/task/TaskRetriever.java
  src/main/java/nutshell/server/service/task/TaskService.java
Labels: :recycle: refac

#46 [feat] Task type별 리스트 조회 GET API 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/dto/task/TodoTaskDto.java
  src/main/java/nutshell/server/exception/code/NotFoundErrorCode.java
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/service/task/TaskRetriever.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/task/TaskUpdater.java
Labels: :zap: feat

#51 [feat] InProgressDay 테이블 추가 및 task 테이블 수정
  src/main/java/nutshell/server/domain/InProgressDay.java
  src/main/java/nutshell/server/domain/Task.java
Labels: :zap: feat

#59 [feat] Task 삭제 DELETE API 구현 완료
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/service/task/TaskService.java
Labels: :zap: feat, v2

#57 ⚡ [feat] Task 생성 POST API 구현 완료
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/domain/TaskStatus.java
  src/main/java/nutshell/server/service/task/TaskService.java
Labels: :zap: feat, v2

#63 [feat] Task List 조회 API 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/dto/task/TasksDto.java
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/repository/TaskStatusRepository.java
  src/main/java/nutshell/server/service/task/TaskRetriever.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/taskStatus/TaskStatusRetriever.java
Labels: :zap: feat, v2

#64 [feat] Task 상세 조회 GET API 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/domain/TimeBlock.java
  src/main/java/nutshell/server/dto/task/TargetDateDto.java
  src/main/java/nutshell/server/dto/task/TaskDto.java
  src/main/java/nutshell/server/repository/TimeBlockRepository.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/timeblock/TimeBlockRetriever.java
Labels: :zap: feat, v2

#23 [feat] TimeBlock CRUD 및 구글 캘린더 연동 및 조회 구현 완료
  build.gradle
  dump.rdb
  src/main/java/nutshell/server/advice/GlobalExceptionHandler.java
  src/main/java/nutshell/server/constant/GoogleCalendarConstant.java
  src/main/java/nutshell/server/controller/AuthController.java
  src/main/java/nutshell/server/controller/GoogleCalendarController.java
  src/main/java/nutshell/server/controller/TestController.java
  src/main/java/nutshell/server/controller/TimeBlockController.java
  src/main/java/nutshell/server/controller/UserController.java
  src/main/java/nutshell/server/domain/GoogleCalendar.java
  src/main/java/nutshell/server/domain/GoogleCalender.java
  src/main/java/nutshell/server/domain/Task.java
  src/main/java/nutshell/server/domain/TimeBlock.java
  src/main/java/nutshell/server/domain/User.java
  src/main/java/nutshell/server/dto/auth/JwtTokensDto.java
  src/main/java/nutshell/server/dto/googleCalender/request/CategoriesDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleEmailDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleScheduleDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleSchedulesDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleTokenDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleUserInfo.java
  src/main/java/nutshell/server/dto/task/TaskAssignedDto.java
  src/main/java/nutshell/server/dto/task/TaskDetailEditDto.java
  src/main/java/nutshell/server/dto/timeBlock/request/TimeBlockCreateDto.java
  src/main/java/nutshell/server/dto/timeBlock/request/TimeBlockUpdateDto.java
  src/main/java/nutshell/server/dto/timeBlock/response/TimeBlockDto.java
  src/main/java/nutshell/server/dto/timeBlock/response/TimeBlocksDto.java
  src/main/java/nutshell/server/dto/timeBlock/response/TimeBlocksWithGooglesDto.java
  src/main/java/nutshell/server/dto/user/response/UserDto.java
  src/main/java/nutshell/server/exception/code/BusinessErrorCode.java
  src/main/java/nutshell/server/exception/code/IllegalArgumentErrorCode.java
  src/main/java/nutshell/server/exception/code/NotFoundErrorCode.java
  src/main/java/nutshell/server/repository/GoogleCalendarRepository.java
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/repository/TimeBlockRepository.java
  src/main/java/nutshell/server/service/auth/AuthService.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarRemover.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarRetriever.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarSaver.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarService.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarUpdater.java
  src/main/java/nutshell/server/service/task/TaskRetriever.java
  src/main/java/nutshell/server/service/task/TaskUpdater.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockRemover.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockRetriever.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockSaver.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockService.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockUpdater.java
  src/main/java/nutshell/server/service/user/UserRetriever.java
  src/main/java/nutshell/server/service/user/UserService.java
  src/main/java/nutshell/server/utils/JwtUtil.java
Labels: :zap: feat, v2

#66 [feat] Task 설명 수정 PATCH API 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/service/task/TaskService.java
Labels: :zap: feat, v2

#74 [feat] 대시보드에서 기간별로 완료한 일 수, 평균 진행 중인 일 수, 평균 지연율을 조회하는 GET API 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/dto/task/TaskDashboardDto.java
  src/main/java/nutshell/server/exception/code/BusinessErrorCode.java
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/repository/TaskStatusRepository.java
  src/main/java/nutshell/server/service/task/TaskRetriever.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/taskStatus/TaskStatusRetriever.java
Labels: :zap: feat, v2

#73 [feat] googleCalender category 리스트 조회 api 구현
  src/main/java/nutshell/server/controller/GoogleCalendarController.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleCategoriesDto.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarService.java
Labels: :zap: feat

#71 [feat] task 수정 시 마다 timeBlock cascade를 통한 삭제 및 추가 삭제 로직 구현
  src/main/java/nutshell/server/domain/Task.java
  src/main/java/nutshell/server/domain/TaskStatus.java
  src/main/java/nutshell/server/domain/TimeBlock.java
  src/main/java/nutshell/server/domain/User.java
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/repository/TaskStatusRepository.java
  src/main/java/nutshell/server/repository/TimeBlockRepository.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockRemover.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockRetriever.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockService.java
Labels: :zap: feat, v2

#68 [feat] Task type별 리스트 조회 구현
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/service/task/TaskRetriever.java
  src/main/java/nutshell/server/service/task/TaskService.java
Labels: :zap: feat, v2

#76 [fix] 구글 로그인 api 수정
  src/main/java/nutshell/server/controller/AuthController.java
Labels: :bug: fix

#79 [refac] 함수 네이밍 변경 및 코드 리팩토링
  src/main/java/nutshell/server/advice/GlobalExceptionHandler.java
  src/main/java/nutshell/server/constant/AuthConstant.java
  src/main/java/nutshell/server/constant/GoogleCalendarConstant.java
  src/main/java/nutshell/server/constant/GoogleConstant.java
  src/main/java/nutshell/server/controller/AuthController.java
  src/main/java/nutshell/server/controller/GoogleCalendarController.java
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/controller/TestController.java
  src/main/java/nutshell/server/controller/TimeBlockController.java
  src/main/java/nutshell/server/dto/SocialLoginResponse.java
  src/main/java/nutshell/server/dto/auth/response/JwtTokensDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleScheduleDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleSchedulesDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleTokenDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleUserInfo.java
  src/main/java/nutshell/server/dto/task/TaskResponse.java
  src/main/java/nutshell/server/dto/task/request/TargetDateDto.java
  src/main/java/nutshell/server/dto/task/request/TaskCreateDto.java
  src/main/java/nutshell/server/dto/task/request/TaskStatusDto.java
  src/main/java/nutshell/server/dto/task/request/TaskUpdateDto.java
  src/main/java/nutshell/server/dto/task/response/TaskDashboardDto.java
  src/main/java/nutshell/server/dto/task/response/TaskDetailDto.java
  src/main/java/nutshell/server/dto/task/response/TasksDto.java
  src/main/java/nutshell/server/dto/task/response/TodoTaskDto.java
  src/main/java/nutshell/server/dto/test/TestDto.java
  src/main/java/nutshell/server/dto/test/TestInput.java
  src/main/java/nutshell/server/dto/timeBlock/request/TimeBlockRequestDto.java
  src/main/java/nutshell/server/dto/timeBlock/request/TimeBlockUpdateDto.java
  src/main/java/nutshell/server/feign/google/GoogleAuthClient.java
  src/main/java/nutshell/server/feign/google/GoogleInfoClient.java
  src/main/java/nutshell/server/feign/google/GoogleReissueClient.java
  src/main/java/nutshell/server/feign/google/GoogleReissueRequest.java
  src/main/java/nutshell/server/feign/google/GoogleUnlinkClient.java
  src/main/java/nutshell/server/feign/google/GoogleUserInfoResponse.java
  src/main/java/nutshell/server/repository/TokenRepository.java
  src/main/java/nutshell/server/service/auth/AuthService.java
  src/main/java/nutshell/server/service/google/GoogleService.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarService.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/task/TaskUpdater.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockService.java
  src/main/java/nutshell/server/service/token/TokenRetriever.java
  src/main/java/nutshell/server/utils/JwtUtil.java
Labels: :recycle: refac

#83 [feat] target area에서 staging area로 할당 로직 추가
  src/main/java/nutshell/server/advice/GlobalExceptionHandler.java
  src/main/java/nutshell/server/constant/AuthConstant.java
  src/main/java/nutshell/server/repository/TaskRepository.java
  src/main/java/nutshell/server/repository/TaskStatusRepository.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/task/TaskUpdater.java
  src/main/java/nutshell/server/service/taskStatus/TaskStatusRetriever.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockService.java
Labels: :zap: feat

#80 [refac] ErrorCode들의 문구를 통일하고 안 쓰는 ErrorCode 삭제
  src/main/java/nutshell/server/advice/GlobalExceptionHandler.java
  src/main/java/nutshell/server/exception/ForbiddenException.java
  src/main/java/nutshell/server/exception/code/BusinessErrorCode.java
  src/main/java/nutshell/server/exception/code/ForbiddenErrorCode.java
  src/main/java/nutshell/server/exception/code/IllegalArgumentErrorCode.java
  src/main/java/nutshell/server/exception/code/InternalServerErrorCode.java
  src/main/java/nutshell/server/exception/code/NotFoundErrorCode.java
  src/main/java/nutshell/server/exception/code/UnAuthorizedErrorCode.java
Labels: :recycle: refac

#86 [feat] P6Spy 의존성 추가
  build.gradle
Labels: :zap: feat

#93 [refac] 스케줄링 쿼리문 리팩토링
  src/main/java/nutshell/server/repository/TaskStatusRepository.java
Labels: :recycle: refac

#97 [fix] DeadLine 날짜 시간 자르는 함수 생성
  src/main/java/nutshell/server/service/task/TaskService.java
Labels: :bug: fix

#100 [feat] 스케줄링 Async 추가
  src/main/java/nutshell/server/config/AsyncConfig.java
  src/main/java/nutshell/server/schedule/ScheduleService.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarService.java
  src/main/java/nutshell/server/service/taskStatus/TaskStatusService.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockService.java
Labels: :zap: feat

#103 [fix] xml 파일 이름 수정 및 내용 추가
  src/main/resources/logback-dev.xml
  src/main/resources/logback.xml
Labels: :bug: fix

#102 [refac] googleCalendar 존재 여부에 따른 db저장 추가
  src/main/java/nutshell/server/exception/code/BusinessErrorCode.java
  src/main/java/nutshell/server/repository/GoogleCalendarRepository.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarRetriever.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarSaver.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarService.java
Labels: :recycle: refac

#105 [fix] request body 대신 param 사용하도록 변경
  src/main/java/nutshell/server/controller/TaskController.java
Labels: :bug: fix

#109 [refac] requestBody 삭제 후 requestParam으로 변경
  src/main/java/nutshell/server/controller/TimeBlockController.java
  src/main/java/nutshell/server/dto/googleCalender/request/CategoriesDto.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarService.java
  src/main/java/nutshell/server/service/timeBlock/TimeBlockService.java
Labels: :recycle: refac

#107 [fix] task 생성 POST API에서 deadline이 null 일 경우도정상 요청 되도록 수정
  src/main/java/nutshell/server/controller/TaskController.java
  src/main/java/nutshell/server/domain/Task.java
  src/main/java/nutshell/server/dto/task/request/TaskCreateDto.java
  src/main/java/nutshell/server/service/task/TaskService.java
  src/main/java/nutshell/server/service/task/TaskUpdater.java
Labels: :bug: fix

#111 [fix] taskRepository DeadLine 제거
  src/main/java/nutshell/server/repository/TaskRepository.java
Labels: :bug: fix

#113 [refac] categories 조회 Json 구조 변경
  src/main/java/nutshell/server/controller/GoogleCalendarController.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleCategoriesDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/GoogleEmailsDto.java
  src/main/java/nutshell/server/dto/googleCalender/response/UserEmailDto.java
  src/main/java/nutshell/server/dto/user/response/UserDto.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarService.java
  src/main/java/nutshell/server/service/user/UserService.java
Labels: :recycle: refac

#115 [fix] logback.xml 파일 수정
  src/main/resources/logback.xml
Labels: :bug: fix

#117 [feat] 동기화 기능 추가 및 카테고리와 스케줄 db 저장 로직 구현
  src/main/java/nutshell/server/config/AsyncConfig.java
  src/main/java/nutshell/server/controller/GoogleCalendarController.java
  src/main/java/nutshell/server/domain/GoogleCategory.java
  src/main/java/nutshell/server/domain/GoogleSchedule.java
  src/main/java/nutshell/server/repository/GoogleCategoryRepository.java
  src/main/java/nutshell/server/repository/GoogleScheduleRepository.java
  src/main/java/nutshell/server/service/google/GoogleService.java
  src/main/java/nutshell/server/service/googleCalendar/GoogleCalendarService.java
  src/main/java/nutshell/server/service/googleCategory/GoogleCategoryRemover.java
  src/main/java/nutshell/server/service/googleCategory/GoogleCategoryRetriever.java
  src/main/java/nutshell/server/service/googleCategory/GoogleCategorySaver.java
  src/main/java/nutshell/server/service/googleSchedule/GoogleScheduleRemover.java
  src/main/java/nutshell/server/service/googleSchedule/GoogleScheduleRetriever.java
  src/main/java/nutshell/server/service/googleSchedule/GoogleScheduleSaver.java
  src/main/java/nutshell/server/service/googleSchedule/GoogleScheduleService.java
Labels: :zap: feat

#119 [feat] 이용자 ID 필드 추가 및 안쓰는 주석 삭제
  src/main/java/nutshell/server/discord/external/DiscordAppender.java
  src/main/java/nutshell/server/discord/filter/MDCFilter.java
  src/main/java/nutshell/server/discord/util/MDCUtil.java
Labels: :zap: feat

#123 [refac] BusinessException 시 로깅 레벨 변경
  src/main/java/nutshell/server/advice/GlobalExceptionHandler.java
  src/main/java/nutshell/server/security/filter/JwtAuthenticationFilter.java
Labels: :recycle: refac
